# Generated by Django 6.0.5 on 2026-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampaignData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("campaign_name", models.CharField(max_length=255)),
                ("channel", models.CharField(max_length=100)),
                ("impressions", models.IntegerField()),
                ("clicks", models.IntegerField()),
                ("conversions", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
