# Generated by Django 6.0.5 on 2026-05-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("created_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveBigIntegerField(default=0)),
                ("upload_success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("campaign_name", models.CharField(max_length=255)),
                ("channel", models.CharField(max_length=100)),
                ("impressions", models.IntegerField()),
                ("clicks", models.IntegerField()),
                ("conversions", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "campaign_name",
                            "date",
                            "channel",
                            "impressions",
                            "clicks",
                            "conversions",
                            "cost",
                            "revenue",
                        ),
                        name="unique_campaign_record",
                    )
                ],
            },
        ),
    ]
